import './style.css';
import {business, products} from './config.js';

const app = document.querySelector('#app');
const image = (id,w=900) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=82`;
const money = n => new Intl.NumberFormat('en-US',{style:'currency',currency:business.currency}).format(n);
const path = () => window.location.pathname.replace(/\/$/,'') || '/';
const slug = path();
const title = (text, eyebrow='THE DETAILS') => `<section class="page-heading wrap"><p class="eyebrow">${eyebrow}</p><h1>${text}</h1></section>`;
const review = (label) => `<span class="review">${label} to be confirmed by the business</span>`;
const productCard = p => `<article class="product-card" data-category="${p.category}"><button class="product-image" data-detail="${p.id}" aria-label="View ${p.name}"><img src="${image(p.image,700)}" loading="lazy" alt="${p.name}"/><span class="view-tag">View details</span></button><div class="product-meta"><span>${p.category}</span><button class="quick-add" data-add="${p.id}" aria-label="Add ${p.name} to bag">+</button></div><h3><button data-detail="${p.id}">${p.name}</button></h3><p class="price">${money(p.price)}</p></article>`;
const footer = `<footer class="footer"><div class="wrap footer-grid"><div><a class="logo footer-logo" href="/"><span class="mark">ec<span>·</span></span><span>ECOM CHRIS</span></a><p>Thoughtfully selected for the everyday.</p><small>DBA: ${business.name} · Business details pending verification</small></div><div><h4>Explore</h4><a href="/shop">Shop all</a><a href="/contact">Contact</a></div><div><h4>Customer care</h4><a href="/shipping">Shipping policy</a><a href="/returns">Cancellation & refunds</a><a href="/privacy">Privacy policy</a><a href="/terms">Terms & conditions</a></div></div><div class="wrap footer-bottom"><span>© ${new Date().getFullYear()} ${business.name}. All rights reserved.</span><span>Made for the moments in between.</span></div></footer>`;
const header = `<div class="announcement">A little more joy in the everyday <span aria-hidden="true">✦</span></div><header class="site-header"><div class="wrap nav"><a class="logo" href="/" aria-label="Ecom Chris home"><span class="mark">ec<span>·</span></span><span>ECOM CHRIS</span></a><nav class="desktop-nav" aria-label="Main navigation"><a href="/" ${slug==='/'?'aria-current="page"':''}>Home</a><a href="/shop" ${slug==='/shop'?'aria-current="page"':''}>Shop</a><a href="/contact" ${slug==='/contact'?'aria-current="page"':''}>Contact</a></nav><div class="nav-actions"><button id="bag-trigger" aria-label="Open bag">Bag <span id="bag-count">0</span></button><button id="menu-trigger" class="menu-trigger" aria-expanded="false" aria-controls="mobile-nav" aria-label="Toggle menu"><span></span><span></span></button></div></div><nav id="mobile-nav" class="mobile-nav" aria-label="Mobile navigation" hidden><a href="/">Home</a><a href="/shop">Shop</a><a href="/contact">Contact</a><a href="/shipping">Shipping</a><a href="/returns">Returns</a></nav></header>`;

function home(){return `<section class="hero"><div class="hero-copy"><p class="eyebrow">WELCOME TO ${business.name.toUpperCase()}</p><h1>Good things for <em>every day.</em></h1><p>Objects to make the ordinary feel a little more considered. Explore our collection and find something that fits your day.</p><a class="button button-light" href="/shop">Explore the collection <span aria-hidden="true">↗</span></a><div class="hero-bottom"><span>01 / 03</span><span>CURATED FOR DAILY LIFE</span></div></div><div class="hero-art"><img src="${image('photo-1490312278390-ab64016e0aa9',1400)}" alt="A sunlit living space with carefully chosen furnishings"/><span class="hero-caption">Find your everyday favorite</span></div></section><section class="marquee" aria-label="Our approach"><div>CONSIDERED FINDS <span>✳</span> EVERYDAY JOY <span>✳</span> MADE TO FIT YOUR LIFE <span>✳</span> CONSIDERED FINDS <span>✳</span> EVERYDAY JOY <span>✳</span></div></section><section class="section wrap"><div class="section-top"><div><p class="eyebrow">THE COLLECTION</p><h2>Find something <em>you love.</em></h2></div><a class="text-link" href="/shop">Shop all products <span aria-hidden="true">↗</span></a></div><div class="products-grid">${products.slice(0,4).map(productCard).join('')}</div><p class="catalog-notice">Preview catalog: products and prices shown are illustrative and will be replaced with the business's actual offerings.</p></section><section class="story"><div class="story-photo"><img src="${image('photo-1441986300917-64674bd600d8',1200)}" loading="lazy" alt="Bright retail space with carefully arranged items"/></div><div class="story-copy"><p class="eyebrow">A BETTER KIND OF EVERYDAY</p><h2>Small details.<br/><em>Big feeling.</em></h2><p>Shopping should feel simple and enjoyable. Ecom Chris brings useful finds together in one place, with clear information to help you choose with confidence.</p><a class="button button-dark" href="/shop">Browse the collection <span aria-hidden="true">↗</span></a></div></section><section class="promise wrap"><div><span class="promise-icon">✳</span><h3>Find your fit</h3><p>Explore a range of everyday categories in one easy place.</p></div><div><span class="promise-icon">◇</span><h3>Know before you buy</h3><p>See product details and prices clearly before making a decision.</p></div><div><span class="promise-icon">↗</span><h3>Questions welcome</h3><p>Our contact page makes it easy to reach the business.</p></div></section><section class="cta"><p class="eyebrow">TAKE A LOOK AROUND</p><h2>Your next favorite is <em>waiting.</em></h2><a class="button button-light" href="/shop">View all products <span aria-hidden="true">↗</span></a></section>`}
function shop(){return `${title('The collection.','DISCOVER THE EDIT')}<section class="wrap shop-intro"><p>Discover considered finds for home, work, and daily life.</p><p class="catalog-notice">Preview catalog: these products and prices are illustrative, pending confirmation by the business.</p><div class="filters" role="group" aria-label="Filter products"><button class="active" data-filter="All" aria-pressed="true">All <span>(${products.length})</span></button>${['Home','Accessories','Tech','Lifestyle'].map(c=>`<button data-filter="${c}" aria-pressed="false">${c}</button>`).join('')}</div><div class="products-grid shop-grid">${products.map(productCard).join('')}</div><p class="empty" hidden>No products in this category yet.</p></section>`}
function contact(){return `${title('Let’s talk.','GET IN TOUCH')}<section class="wrap contact-layout"><div class="contact-lead"><h2>Here to help.</h2><p>Questions about a product, order, or our policies? Contact the business using the details below once they are confirmed.</p><div class="contact-block"><span>PHONE</span>${business.phone?`<a href="tel:${business.phone.replace(/[^+\d]/g,'')}">${business.phone}</a>`:review('Phone number')}</div><div class="contact-block"><span>EMAIL</span>${business.email?`<a href="mailto:${business.email}">${business.email}</a>`:review('Email address')}</div><div class="contact-block"><span>BUSINESS ADDRESS</span>${business.address||review('Business address')}</div><div class="contact-block"><span>SUPPORT HOURS</span>${business.supportHours||review('Support hours')}</div></div><aside class="contact-aside"><span class="large-star">✳</span><h3>Good to know</h3><p>For a question about an order, include the order reference and the email used at purchase. Please do not send payment card details through email.</p><div class="aside-links"><a href="/shipping">Shipping details <span>↗</span></a><a href="/returns">Cancellations & refunds <span>↗</span></a></div></aside></section>`}
const policyIntro = `<p class="policy-alert">This is a draft policy for review. The business must confirm its legal name, contact details, selling region, fulfillment times, return window, and actual practices before publishing it for customers or submitting it to a merchant provider.</p>`;
function policy(kind){const data={
  '/privacy': ['Privacy policy',`<h2>Information we collect</h2><p>When you contact us or place an order through a future checkout, we may receive your name, contact details, delivery information, and order details. A payment provider may process payment information under its own privacy notice; this website currently does not accept payments or collect card information.</p><h2>How we use information</h2><p>We use information to respond to inquiries, fulfill purchases when ordering is enabled, provide customer support, maintain site security, and meet applicable legal obligations. We do not sell personal information.</p><h2>Cookies and analytics</h2><p>This preview website does not set analytics or advertising cookies. The bag uses local storage on your device and can be cleared through your browser settings. Product images are served by Unsplash, which may receive basic request data when images load.</p><h2>Sharing and retention</h2><p>When operations begin, information may be shared with service providers needed for fulfillment, delivery, payments, or legal compliance. Retention periods and providers must be confirmed by the business before launch.</p><h2>Your choices</h2><p>Contact us to request access, correction, or deletion of information, subject to applicable law. Verified contact details will appear on the <a href="/contact">contact page</a>.</p>`],
  '/terms': ['Terms & conditions',`<h2>Using this website</h2><p>These terms describe use of the Ecom Chris website. Product descriptions, availability, and prices shown in this preview are illustrative and do not constitute an offer to sell. Orders and payments are not currently accepted through this site.</p><h2>Products and pricing</h2><p>Before commerce is enabled, the business will publish verified product details, currency, taxes, availability, and final prices. Any final purchase terms will be displayed before an order is placed.</p><h2>Orders and payments</h2><p>Checkout is unavailable in this version. Adding items to a local bag does not create an order, reserve stock, or charge a customer.</p><h2>Site content</h2><p>Text, design, and branding on this website may not be reused without permission. Third-party product photographs in this preview are illustrative and should be replaced with licensed images of actual goods.</p><h2>Changes and questions</h2><p>Terms may be updated when the business is ready to trade. For questions, use the <a href="/contact">contact page</a>. The business should obtain legal review for its operating jurisdiction before relying on these terms.</p>`],
  '/returns': ['Cancellation & refund policy',`<h2>Before ordering</h2><p>This website currently has no checkout and does not accept orders or payments. No purchase can be canceled or refunded through this preview.</p><h2>Future cancellation process</h2><p>The business will confirm when an order can be canceled, how to request cancellation, and whether an order in fulfillment can be changed before accepting purchases.</p><h2>Returns and eligibility</h2><p>The return window, condition requirements, exclusions, return address, shipping responsibility, and any restocking fee are awaiting confirmation. These details must be published before accepting orders.</p><h2>Refund timing</h2><p>Approved refunds, when trading begins, should be returned to the original payment method. Processing time depends on the payment provider and the final business policy, which must be confirmed.</p><h2>Damaged or incorrect items</h2><p>Customers should be given a clear way to report a damaged, defective, or incorrect item. Verified instructions and contact details will be added here before launch.</p>`],
  '/shipping': ['Shipping policy',`<h2>Where we ship</h2><p>The business has not yet confirmed its shipping destinations. Delivery options will be displayed before orders can be placed.</p><h2>Processing and delivery</h2><p>Order processing times, carriers, delivery estimates, and cutoffs are awaiting confirmation. Estimated delivery times should be stated separately from processing time.</p><h2>Shipping costs</h2><p>Rates, any free-shipping threshold, and applicable taxes or duties will be shown before a customer completes a purchase. No shipping charge is collected on this preview site.</p><h2>Tracking and delays</h2><p>When fulfillment is available, the business will state whether tracking is provided and how customers can report a missing package or delivery issue.</p><h2>Questions</h2><p>See the <a href="/contact">contact page</a> for business contact information once verified.</p>`]
}; const [heading,sections]=data[kind];return `${title(heading,'CUSTOMER INFORMATION')}<article class="wrap policy"><div class="policy-meta"><span>${business.name}</span><span>Draft updated ${business.updated}</span></div>${policyIntro}${sections}<div class="policy-end">Have a question? <a href="/contact">Get in touch ↗</a></div></article>`}
function notFound(){return `${title('Page not found.','404')}<section class="wrap not-found"><p>We couldn’t find that page.</p><a class="button button-dark" href="/">Back to home</a></section>`}
const pages={'/':home,'/shop':shop,'/contact':contact,'/privacy':()=>policy('/privacy'),'/terms':()=>policy('/terms'),'/returns':()=>policy('/returns'),'/shipping':()=>policy('/shipping')};
app.innerHTML = `${header}<main id="main">${(pages[slug]||notFound)()}</main>${footer}<div class="overlay" id="overlay" hidden></div><aside class="drawer" id="bag-drawer" aria-label="Shopping bag" aria-modal="true" role="dialog" hidden><div class="drawer-head"><div><span class="eyebrow">YOUR SELECTION</span><h2>Shopping bag</h2></div><button class="close" id="bag-close" aria-label="Close bag">×</button></div><div id="bag-items"></div><div class="drawer-foot"><div class="total"><span>Subtotal</span><strong id="bag-total">$0.00</strong></div><p>This is a preview bag. Ordering and payment are not available yet.</p><a href="/contact" class="button button-dark">Contact the business <span>↗</span></a></div></aside><div class="modal" id="product-modal" role="dialog" aria-modal="true" aria-label="Product details" hidden></div><div class="toast" id="toast" role="status" aria-live="polite"></div>`;
document.title = `${slug==='/'?'Ecom Chris':slug==='/shop'?'Shop':slug==='/contact'?'Contact':slug==='/returns'?'Cancellation & refunds':slug==='/shipping'?'Shipping policy':slug==='/privacy'?'Privacy policy':slug==='/terms'?'Terms & conditions':'Page not found'} | Ecom Chris`;

let bag; try {bag=JSON.parse(localStorage.getItem('ecomchris-bag')||'{}')} catch {bag={}};
const save=()=>{localStorage.setItem('ecomchris-bag',JSON.stringify(bag));renderBag()};
function renderBag(){const count=Object.values(bag).reduce((a,b)=>a+b,0);document.querySelector('#bag-count').textContent=count;const entries=Object.entries(bag).filter(([id,n])=>n>0&&products.some(p=>p.id===id));document.querySelector('#bag-items').innerHTML=entries.length?entries.map(([id,n])=>{const p=products.find(p=>p.id===id);return `<div class="bag-item"><img src="${image(p.image,180)}" alt=""/><div><strong>${p.name}</strong><span>${money(p.price)}</span><div class="qty"><button data-qty="${id}" data-delta="-1" aria-label="Remove one ${p.name}">−</button><span>${n}</span><button data-qty="${id}" data-delta="1" aria-label="Add one ${p.name}">+</button></div></div></div>`}).join(''):'<div class="bag-empty"><span>◇</span><h3>Your bag is empty</h3><p>Find something you like in the collection.</p><a href="/shop">Explore products ↗</a></div>';document.querySelector('#bag-total').textContent=money(entries.reduce((sum,[id,n])=>sum+products.find(p=>p.id===id).price*n,0))}
renderBag();
let priorFocus=null;const overlay=document.querySelector('#overlay'),drawer=document.querySelector('#bag-drawer'),modal=document.querySelector('#product-modal');
function closePanels(){drawer.hidden=true;modal.hidden=true;overlay.hidden=true;document.body.classList.remove('locked');priorFocus?.focus();priorFocus=null}
function openPanel(el){priorFocus=document.activeElement;overlay.hidden=false;el.hidden=false;document.body.classList.add('locked');el.querySelector('button')?.focus()}
const toast=document.querySelector('#toast');let toastTimer;function notify(s){toast.textContent=s;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2500)}
document.querySelector('#bag-trigger').addEventListener('click',()=>openPanel(drawer));document.querySelector('#bag-close').addEventListener('click',closePanels);overlay.addEventListener('click',closePanels);document.addEventListener('keydown',e=>{if(e.key==='Escape')closePanels();if(e.key==='Tab'&&!overlay.hidden){const panel=!modal.hidden?modal:drawer;const focusable=[...panel.querySelectorAll('a[href],button:not([disabled])')];if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
const menu=document.querySelector('#menu-trigger'),mobile=document.querySelector('#mobile-nav');menu.addEventListener('click',()=>{mobile.hidden=!mobile.hidden;menu.setAttribute('aria-expanded',String(!mobile.hidden))});
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){bag[add.dataset.add]=(bag[add.dataset.add]||0)+1;save();notify('Added to your bag');return}const qty=e.target.closest('[data-qty]');if(qty){bag[qty.dataset.qty]=Math.max(0,(bag[qty.dataset.qty]||0)+Number(qty.dataset.delta));save();return}const detail=e.target.closest('[data-detail]');if(detail){const p=products.find(p=>p.id===detail.dataset.detail);modal.innerHTML=`<button class="modal-close close" aria-label="Close product details">×</button><img src="${image(p.image,950)}" alt="${p.name}"/><div class="modal-copy"><p class="eyebrow">${p.category} / ${p.badge}</p><h2>${p.name}</h2><p>${p.description}</p><strong>${money(p.price)}</strong><p class="fineprint">Preview product and price — details to be confirmed.</p><button class="button button-dark" data-add="${p.id}">Add to bag <span>+</span></button></div>`;modal.querySelector('.modal-close').addEventListener('click',closePanels);openPanel(modal)}});
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{const category=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});document.querySelectorAll('.product-card').forEach(card=>card.hidden=category!=='All'&&card.dataset.category!==category)}));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.section,.story,.promise,.cta,.product-card,.page-heading,.policy,.contact-layout').forEach(el=>{el.classList.add('reveal');observer.observe(el)});
